version: '3'

services:
  react:
    image: jav13r/nodejs:8.11.3
    ports:
      - '3000:3000'
    environment:
        - HOST=0.0.0.0
    command: 'yarn start prevent.env.HOST'
    volumes:
      - $PWD:/usr/src/apps
    working_dir: /usr/src/apps
