version: '3'

services:
  java:
    image: jav13r/java:8.0
    ports:
      - "127.0.0.1:8888:8080"
    command: java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
    volumes:
      - $PWD:/usr/src/demo
    working_dir: /usr/src/demo
