version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - $PWD/docker-config/nginx/default:/etc/nginx/conf.d/default.conf
      - $PWD/docker-config/nginx/logs/nginx-error.log:/var/log/nginx/error.log
      - $PWD/docker-config/nginx/logs/nginx-access.log:/var/log/nginx/access.log
      - $PWD:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html

  phpfpm:
    image: jav13r/php:7.0.30-fpm
    ports:
      - '9000:9000'
    working_dir: /usr/share/nginx/html
    volumes:
      - $PWD:/usr/share/nginx/html
      - $PWD/docker-config/phpfpm/php.ini:/usr/local/etc/php/php.ini

  composer:
    image: composer:latest
    command: composer install
    volumes:
      - $PWD:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    depends_on:
      - nginx
      - phpfpm

  node:
    image: jav13r/nodejs:8.11.3
    command: yarn install
    volumes:
      - $PWD:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
